### ISSUE TITLE
Even if you don't need it, your DB needs the "hstore" extension to be installed

### ISSUE THREAD

**Issue by brunobord** [novafloss/populous#24]
Running a generation on a fresh database with no specific extension installed leads to this:

```
psycopg2.ProgrammingError: hstore type not found in the database. please install it from your 'contrib/hstore.sql' file
```

Fair enough. I don't know which one of these options is interesting:

* Make the use of hstore optional, thus allowing to use populous without hstore installed the db. Eventually throw an error if you try to add a hstore field in your blueprints.
* Make the use of hstore mandatory, but warn the user first in the doc and by gracefully send an error message when trying to a connect to a hstore-less db,

**Comment by k4nar** [comment]
Yes, hstore should be optional.

I'm pretty sure this is easy to handle.
